commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: jhipsterlintest2

resources:
  - namespace.yml
  # Individual apps
  - jhipsterlintestapplication/jhipsterlintestapplication-deployment.yml
  - jhipsterlintestapplication/jhipsterlintestapplication-service.yml
  - jhipsterlintestapplication/jhipsterlintestapplication-mongodb.yml
  - jhipsterlintestgateway/jhipsterlintestgateway-deployment.yml
  - jhipsterlintestgateway/jhipsterlintestgateway-service.yml
  - jhipsterlintestgateway/jhipsterlintestgateway-mongodb.yml
  - jhipsterlintestgateway/jhipsterlintestgateway-elasticsearch.yml
  - jhipsterlintestgateway/jhipsterlintestgateway-ingress.yml
  # messagebroker
  - messagebroker/kafka.yml
  # monitoring elk
  - console/jhipster-elasticsearch.yml
  - console/jhipster-logstash.yml
  - console/jhipster-console.yml
  - console/jhipster-dashboard-console.yml
  - console/jhipster-zipkin.yml
  # service discovery eureka/consul
  - registry/jhipster-registry.yml
  - registry/application-configmap.yml

patchesJson6902:
