apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: cilincner/jhipsterlintestapplication
      context: ./jhipster-lintest-application
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
